import assert from 'node:assert/strict';
import { DEFAULT_2026_PARAMS as P, calculateWageDeduction, calculateMinimumPaymentCoverage } from '../src/lib/calculations2026.js';
import { createDefaultData, migrateData, caseStatus, confirmSection, sectionReviewed, incomeReady, setIncomeSources, confirmNoIncome, optionalOpen, toggleOptional, OPTIONAL_FIELDS, formatKc, readStored, writeStored, flowFor } from '../src/kalkulacka/caseState.js';
import { calculateCase, calculatePerson, groupPayers, moveIncomeToPayer, removeIncomeSource } from '../src/kalkulacka/calculateCase.js';
let passed = 0;
const test = (name,fn)=>{fn();console.log(`OK ${++passed}: ${name}`);};
const base = (a=30000,b=25000)=>({...createDefaultData(),prijmy1:[{id:'a',typ:'mzda',castka:a,pridelenaNezabavitelna:''}],prijmy2:[{id:'b',typ:'mzda',castka:b,pridelenaNezabavitelna:''}],dluhyNezajistene:600000});
function reviewed(d,mode='jednotlivec',params=P) {for(const step of flowFor(d,mode,calculateCase(d,params,mode))) d=confirmSection(d,mode,step,params);return d;}
const state = (d,mode='jednotlivec',p=P)=>caseStatus(d,mode,calculateCase(d,p,mode),p);
const mp = allocations=>({...base(),vicePlatcu1:true,prijmy1:allocations.map((v,i)=>({id:`p${i}`,typ:'mzda',castka:i===0?20000:30000,pridelenaNezabavitelna:v}))});

test('F01: skutečné samostatné srážky plátců se sčítají na 23930',()=>{const r=calculateCase(mp([7051,7051])).insJ;assert(r.multiPayerExact);assert.equal(r.srazka,23930);assert.equal(r.payerBreakdown.reduce((sum,p)=>sum+p.result.srazka,0),r.srazka);for(const item of r.payerBreakdown)assert.equal(2*item.result.tretina+item.result.plneZabavitelna,item.result.srazka);});
test('F02: prázdné přidělení není nula ani úplné rozdělení',()=>{for(const missing of ['',null,undefined,' '])assert(!calculateCase(mp([14102,missing])).insJ.multiPayerExact);});
test('F02: výslovná nula je platná; rozdíl 1 Kč ani 0,01 Kč nikoli',()=>{assert(calculateCase(mp([14102,0])).insJ.multiPayerExact);assert(!calculateCase(mp([14101,0])).insJ.multiPayerExact);assert(!calculateCase(mp([14102.01,0])).insJ.multiPayerExact);});
test('F02: nový nevyplněný řádek blokuje dokončení',()=>{const d=base();d.prijmy1.push({id:'new',typ:'mzda',castka:'',pridelenaNezabavitelna:''});assert(!state(reviewed(d)).canExport);});
test('F01/F07: více příjmů stejného plátce má jednu srážku a jednu náhradu',()=>{const d=mp([7051,7051]);d.prijmy1[0].castka=10000;d.prijmy1[0].uplatnitPausal=true;d.prijmy1[1].uplatnitPausal=true;d.prijmy1.push({id:'wage2',platceId:'p0',typ:'dpp_dpc',castka:10000,pridelenaNezabavitelna:''});const r=calculateCase(d,P,'nezabavitelna').ex;assert.equal(groupPayers(d.prijmy1).length,2);assert.equal(r.payerBreakdown.length,2);assert.equal(r.nahradaPlatci,100);});
test('F01: plátce pod přidělenou částkou má 0; částka se sama nepřevádí',()=>{const d=mp([7051,7051]);d.prijmy1[0].castka=1000;const r=calculateCase(d).insJ;assert.equal(r.payerBreakdown[0].result.srazka,0);assert(r.allocationUnused);assert(state(d).warnings.some(w=>w.includes('nepřesouvá')));});
test('F03: neplatné rodinné počty blokují všechny režimy a výstupy',()=>{for(const mode of ['jednotlivec','manzele','nezabavitelna']){let d=base();d.vyzivovaneOsoby1=1;d.osobySVykonemProVyzivne1=5;d=reviewed(d,mode);assert(!state(d,mode).canExport);assert(state(d,mode).errors.some(e=>e.field==='osobySVykonemProVyzivne1'));}});
test('F03: záporné, desetinné a nečíselné počty nejsou tiše opraveny',()=>{for(const value of [-1,1.2,'abc',Infinity]) {const d={...base(),vyzivovaneOsoby1:value};assert(state(d).errors.some(e=>e.field==='vyzivovaneOsoby1'));assert.equal(d.vyzivovaneOsoby1,value);}});
test('F03: každého manžela validujeme samostatně',()=>{const d={...base(),spolecneDeti:2,osobySVykonemProVyzivne1:3,osobySVykonemProVyzivne2:1};const e=state(d,'manzele').errors;assert(e.some(x=>x.field==='osobySVykonemProVyzivne1'));assert(!e.some(x=>x.field==='osobySVykonemProVyzivne2'));});
for(const field of Object.keys(OPTIONAL_FIELDS)) test(`F04: účinné starší pole ${field} je vždy viditelné`,()=>{assert(optionalOpen({[field]:10,[OPTIONAL_FIELDS[field]]:false},field));});
test('F04: výslovné vypnutí maže jen dané pole, ne jiné skutečnosti',()=>{const d={...base(),spolecneDeti:2,osobySVykonemProVyzivne1:2,bezneMesicniVyzivne1:2000,bezneMesicniVyzivne2:1000};const n=toggleOptional(d,'spolecneDeti',false);assert.equal(n.osobySVykonemProVyzivne1,2);const next=toggleOptional(d,'bezneMesicniVyzivne1',false);assert.equal(next.bezneMesicniVyzivne2,1000);assert.equal(next.bezneMesicniVyzivne1,0);});
test('F04: neznámým přepínačem nelze měnit libovolné pole',()=>assert.throws(()=>toggleOptional(base(),'prijmy1',false)));
test('F04: změna příjmu nesmaže příspěvek, jeho editor zůstane ve flow',()=>{const d={...base(15000),povolitPlneniTretiOsoby1:true,pravidelnePlneniTretiOsoby1:2000};const next=setIncomeSources(reviewed(d),1,[{id:'a',typ:'mzda',castka:30000}]);assert.equal(next.pravidelnePlneniTretiOsoby1,2000);assert(state(next).flow.includes('minimum'));assert(!sectionReviewed(next,'jednotlivec','minimum',P));});
test('F05: nula není prázdno ani dotknutí se pole',()=>{let d=base('');assert(!incomeReady(d,1));d=setIncomeSources(d,1,[{id:'a',typ:'mzda',castka:20000}]);assert(incomeReady(d,1));d=setIncomeSources(d,1,[{id:'a',typ:'mzda',castka:''}]);assert(!incomeReady(d,1));assert(!d.bezPostizitelnehoPrijmu1);});
test('F05: výslovná nula je persistentní a společná oběma rozhraním',()=>{let d=confirmNoIncome(base(),1,true);assert(incomeReady(d,1));d=migrateData(JSON.parse(JSON.stringify(d)));assert(incomeReady(d,1));assert(state(reviewed(d)).canExport);assert(state(reviewed(d,'manzele'),'manzele').canExport);});
test('F05: dvě výslovné nuly neblokují chráněné příjmy nebo pomoc',()=>{let d=confirmNoIncome(confirmNoIncome(base(),1,true),2,true);d={...d,chranenePrijmy1:12000,povolitPlneniTretiOsobyM:true,pravidelnePlneniTretiOsobyM:4000};const s=state(reviewed(d,'manzele'),'manzele');assert(s.canExport);assert.equal(calculateCase(d,P,'manzele').coverageM.finalDeficit,0);});
test('F05: staré výchozí nuly nelze prohlásit za vědomě potvrzené',()=>{const old={prijmy1:[{id:'a',typ:'mzda',castka:0}],dluhyNezajistene:0};const d=migrateData(old);assert.equal(d.prijmy1[0].castka,'');assert.equal(d.dluhyNezajistene,'');assert(!incomeReady(d,1));});
test('F05: legitimní dřívější potvrzení nuly se migruje',()=>{const d=migrateData({prijmy1:[{id:'a',typ:'mzda',castka:0}],desktopManzeleBezPrijmu1:true});assert(incomeReady(d,1));});
test('F06: export vyžaduje kontrolu všech oddílů a po změně se zneplatní',()=>{let d=base();assert(!state(d).canExport);d=reviewed(d);assert(state(d).canExport);d={...d,bezneMesicniVyzivne1:2000};assert(!state(d).canExport);});
test('F07: žádný důchod, nemocenské, PPM ani podpora nemá náhradu',()=>{for(const typ of ['starobni','invalidni1','invalidni2','invalidni3','sirotci','nemocenske','podpora']){const d={...base(17000),prijmy1:[{id:'p',typ,castka:17000,uplatnitPausal:true}],uplatnitPausalPlatce:true,pocetExekuci:'4+'};assert.equal(calculateCase(d,P,'nezabavitelna').ex.nahradaPlatci,0);}});
test('F07: u důchodu 17000 odchází 966, nikoli 916',()=>{const d={...base(),prijmy1:[{id:'p',typ:'starobni',castka:17000,uplatnitPausal:true}],pocetExekuci:'4+'};const r=calculateCase(d,P,'nezabavitelna').ex;assert.equal(r.srazka,966);assert.equal(r.srazkaCista,966);});
test('F07: u mzdy při potvrzeném nároku zůstává náhrada funkční',()=>{const d=base(20000);d.prijmy1[0].uplatnitPausal=true;assert.equal(calculateCase(d,P,'nezabavitelna').ex.nahradaPlatci,50);});
test('F08: změna odměny správce nepřepisuje důchodovou výjimku',()=>{for(const fee of [900,1089,2000]){const r=calculateWageDeduction({prijem:17000,duchodPovinny:true,pocetExekuci:'4+'},{...P,odmenaSpravceJednotlivec:fee});assert.equal(r.srazka,966);}});
test('F08: vlastní parametry jsou označené a ruší potvrzení',()=>{const d=reviewed(base());const s=state(d,'jednotlivec',{...P,odmenaSpravceJednotlivec:900});assert(s.changedParams.includes('odmenaSpravceJednotlivec'));assert(s.warnings.length);assert(!s.canExport);});
test('F09: prognóza zachovává původní metodiku bez příspěvku',()=>{const d={...base(15000),povolitPlneniTretiOsoby1:true,pravidelnePlneniTretiOsoby1:2000};const r=calculateCase(d);assert.equal(r.coverageJ.finalDeficit,0);assert.equal(r.proVeriteleJ,0);assert.equal(r.uspokojeniJ,0);});
test('F10: neznámý dluh není nula procent, lze vydat omezený výsledek',()=>{const d=reviewed({...base(),dluhNeznamy:true,dluhyNezajistene:''});assert(state(d).canExport);assert(!state(d).debtKnown);});
test('F10: potvrzení editovaného oddílu nezneplatní nezměněné oddíly',()=>{let d=reviewed(base());d={...d,vyzivovaneOsoby1:1};assert(!sectionReviewed(d,'jednotlivec','family',P));assert(sectionReviewed(d,'jednotlivec','other',P));d=confirmSection(d,'jednotlivec','family',P);assert(state(d).canExport);});
test('F11: chybějících 0,40 Kč se nezobrazí jako 0 Kč',()=>{const d={...base(15000),povolitPlneniTretiOsoby1:true,pravidelnePlneniTretiOsoby1:1579.6};const r=calculateCase(d);assert.equal(r.coverageJ.finalDeficit,0.4);assert(formatKc(r.coverageJ.finalDeficit).includes('0,4'));assert(formatKc(1633.5).includes(',5'));assert.notEqual(formatKc(0.001),'0 Kč');});
test('F11: matematicky přesné centové krytí nevytváří zbytek z floating point',()=>{assert.equal(calculateMinimumPaymentCoverage({statutoryDeduction:0.1,thirdPartyContribution:0.2,requiredMinimum:0.3}).finalDeficit,0);});
test('F11: peněžní vstupy s více než dvěma desetinnými místy jsou odmítnuty',()=>{const d={...base(),chranenePrijmy1:0.001};assert(state(d).errors.some(e=>e.field==='chranenePrijmy1'));});
test('F12: selhání čtení/zápisu je zachyceno, nesestřelí aplikaci',()=>{const storage={getItem(){throw new Error('Denied');},setItem(){throw new Error('Quota');}};assert.equal(writeStored(storage,'data',base()),false);assert(readStored(storage,'data',{}).error);});
test('F12: poškozené JSON a schéma jsou rozpoznány',()=>{assert(readStored({getItem:()=>'{broken'},'data',null).error);assert.throws(()=>migrateData({prijmy1:'bad'}));assert.throws(()=>migrateData({prijmy1:[null]}));assert.throws(()=>migrateData({partnerProNezabavitelnou1:'false'}));});
test('Referenční případy z auditu zůstávají stejné',()=>{const a=calculateCase(base());assert.equal(a.insJ.srazka,10598);assert.equal(a.insJ.kVyplate,19402);const b=calculateCase({...base(),spolecneDeti:2},P,'manzele');assert.equal(b.srazkaCelkemM,8462);assert.equal(b.kVyplateCelkemM,46538);assert.equal(calculateCase(base(),P,'nezabavitelna').ex.srazka,5299);});
test('F01/F02: změna pořadí/skupiny příjmů nepřepíše přidělení jiného plátce',()=>{let rows=mp([7051,7051]).prijmy1;rows=moveIncomeToPayer(rows,'p0','p1');assert.equal(groupPayers(rows).length,1);assert.equal(groupPayers(rows)[0].source.pridelenaNezabavitelna,7051);rows=moveIncomeToPayer(rows,'p0','new-payer');assert.equal(groupPayers(rows)[0].source.pridelenaNezabavitelna,'');assert.equal(groupPayers(rows)[1].source.pridelenaNezabavitelna,7051);});
test('F01/F02: odebrání první položky nepřipraví zbylý příjem plátce o přidělení',()=>{const old=[{id:'a',typ:'mzda',castka:10000,pridelenaNezabavitelna:7051,uplatnitPausal:true},{id:'b',platceId:'a',typ:'dpp_dpc',castka:10000},{id:'c',typ:'mzda',castka:30000,pridelenaNezabavitelna:7051}];const next=removeIncomeSource(old,'a');assert.equal(next[0].pridelenaNezabavitelna,7051);assert.equal(next[0].uplatnitPausal,true);assert.equal(next[1].pridelenaNezabavitelna,7051);});
test('F05/F10: načtení zachová ID plátců, rozdělení i platná potvrzení',()=>{let d=mp([7051,7051]);d.prijmy1.push({id:'contract',platceId:'p0',typ:'dpp_dpc',castka:1000,pridelenaNezabavitelna:''});d=reviewed(d);const saved=migrateData(JSON.parse(JSON.stringify(d)));assert.deepEqual(saved.prijmy1,d.prijmy1);assert(state(saved).canExport);assert.equal(calculateCase(saved).insJ.srazka,calculateCase(d).insJ.srazka);});
test('F10: potvrzení náhrady v exekuci nezacyklí kontrolu již zadaného příjmu',()=>{let d=reviewed(base(),'nezabavitelna');d={...d,prijmy1:d.prijmy1.map(s=>({...s,uplatnitPausal:true}))};assert(sectionReviewed(d,'nezabavitelna','income',P));assert(!sectionReviewed(d,'nezabavitelna','execution',P));d=confirmSection(d,'nezabavitelna','execution',P);assert(state(d,'nezabavitelna').canExport);});

if (process.argv.includes('--render')) {
  const {createServer} = await import('vite');
  const React = (await import('react')).default;
  const {renderToStaticMarkup} = await import('react-dom/server');
  const vite=await createServer({configFile:false,server:{middlewareMode:true},appType:'custom',esbuild:{jsx:'transform'}});
  try {
    const {default:Report,buildCalculationShareText}=await vite.ssrLoadModule('/src/kalkulacka/PrintableCalculationReport.jsx');
    const {default:Breakdown}=await vite.ssrLoadModule('/src/kalkulacka/CalculationBreakdown.jsx');
    const {default:Fields}=await vite.ssrLoadModule('/src/kalkulacka/CaseFields.jsx');
    const {default:Results}=await vite.ssrLoadModule('/src/kalkulacka/CaseResults.jsx');
    const {DesktopForm}=await vite.ssrLoadModule('/src/kalkulacka/WorkflowForms.jsx');
    const render=(C,d,mode='jednotlivec',extra={})=>renderToStaticMarkup(React.createElement(C,{data:d,mode,results:calculateCase(d,P,mode),params:P,setData:()=>{},...extra}));
    test('Render F01: každá rovnice ukazuje skutečné mezivýpočty plátce',()=>{const text=renderToStaticMarkup(React.createElement(Breakdown,{result:calculateCase(mp([7051,7051])).insJ}));assert(text.includes('Plátce 1'));assert(text.includes('Plátce 2'));assert(text.includes('23 930'));assert(!text.includes('10 507'));});
    test('Render F01: nízký příjem není záporná rovnice zakončená nulou',()=>{const text=renderToStaticMarkup(React.createElement(Breakdown,{result:calculateCase(base(1000)).insJ}));assert(text.includes('nepřesahuje'));});
    test('Render F06: neplatný Ctrl+P report neobsahuje hotové částky',()=>{const text=render(Report,reviewed({...base(),osobySVykonemProVyzivne1:5}));assert(text.includes('Výpočet nelze vydat'));assert(!text.includes('10 598'));});
    test('Render F06: sdílení neplatného nebo nepotvrzeného zadání odmítá',()=>{for(const d of [base(),reviewed({...base(),osobySVykonemProVyzivne1:5})]) assert.throws(()=>buildCalculationShareText({mode:'jednotlivec',data:d,results:calculateCase(d),params:P}));});
    test('Render F04: pole vymáhání je vidět i bez ostatních závislých osob',()=>{const d={...base(),partnerProNezabavitelnou1:true,osobySVykonemProVyzivne1:1};d.prijmy1[0].typ='starobni';const text=render(Fields,d,'jednotlivec',{step:'family',errors:[]});assert(text.includes('name="osobySVykonemProVyzivne1"'));});
    test('Render F09: modelové omezení je přímo ve výsledku, tisku a sdílení',()=>{const d=reviewed({...base(15000),povolitPlneniTretiOsoby1:true,pravidelnePlneniTretiOsoby1:2000});for(const text of [render(Report,d),render(Results,d),buildCalculationShareText({mode:'jednotlivec',data:d,results:calculateCase(d),params:P})]){assert(text.includes('nezahrnuje'));assert(text.includes('2 000'));}});
    test('Render F10: neznámý dluh nevede na nula procent',()=>{const d=reviewed({...base(),dluhyNezajistene:'',dluhNeznamy:true});const text=render(Report,d);assert(text.includes('Odhad zatím nelze určit'));assert(!text.includes('0.0 %'));});
    test('Render F10: nový desktop odkrývá pole opravdu postupně',()=>{const text=render(DesktopForm,createDefaultData());assert(!text.includes('data-step="family"'));assert(text.includes('data-step="income"'));});
    test('Render F10: potvrzení příjmu odkryje rodinu, ne další prázdné oddíly',()=>{let d=base();d.dluhyNezajistene='';d=confirmSection(d,'jednotlivec','income',P);const text=render(DesktopForm,d);assert(text.includes('data-step="family"'));assert(!text.includes('data-step="other"'));});
  } finally {await vite.close();}
}
console.log(`Audit repair checks passed: ${passed}`);
