import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { DEFAULT_2026_PARAMS as params } from '../src/lib/calculations2026.js';
import { createDefaultData, confirmSection, flowFor, caseStatus, toggleOptional } from '../src/kalkulacka/caseState.js';
import { calculateCase } from '../src/kalkulacka/calculateCase.js';
const catalogue = JSON.parse(fs.readFileSync('src/kalkulacka/approvedHelp.json','utf8'));
let count = 0;
function test(name, run) { run(); console.log(`OK ${++count}: ${name}`); }
assert.equal(catalogue.sourceCommit,'1ad8344381a6373ec2017d90b8b0dc3b901354a7');
assert.equal(catalogue.plainCommit,'6e95c5ecc03dedbee10b71fb6b050402c2272f61');
for (const [key, entry] of Object.entries(catalogue.entries)) {
  test(`Doslovné znění ${key}`, () => {
    assert.equal(createHash('sha256').update(entry.plain+'\n'+entry.legal).digest('hex'), entry.sha256);
    assert(entry.plain.length > 15); assert(Number.isInteger(entry.sourceLine));
    assert(!entry.plain.includes('${'));
  });
}
// With complete local Git history, compare the actual approved version, not
// a snapshot generated by the same current UI code. No network requests.
if (process.argv.includes('--history')) {
  const historical = execFileSync('git',['show',`${catalogue.sourceCommit}:${catalogue.sourcePath}`],{encoding:'utf8'});
  const approvedPlain = execFileSync('git',['show',`${catalogue.plainCommit}:${catalogue.sourcePath}`],{encoding:'utf8'});
  test('Zdrojový soubor odpovídá historickému otisku',()=>assert.equal(createHash('sha256').update(historical).digest('hex'),catalogue.sourceSha256));
  for (const [key,e] of Object.entries(catalogue.entries)) test(`Historický původ ${key}`,()=>{
    assert(approvedPlain.includes(e.plain));
    const span=historical.split('\n').slice(Math.max(0,e.sourceLine-6),e.sourceLine).join('\n').replaceAll('\\n','\n');
    assert(span.includes(e.plain)); if(e.legal) assert(span.includes(e.legal));
  });
}
const React = (await import('react')).default;
const { renderToStaticMarkup } = await import('react-dom/server');
const { createServer } = await import('vite');
const server=await createServer({configFile:false,server:{middlewareMode:true},appType:'custom',esbuild:{jsx:'transform'},optimizeDeps:{noDiscovery:true,include:[]}});
try {
  const { default: Help } = await server.ssrLoadModule('/src/kalkulacka/ApprovedHelp.jsx');
  const { default: Fields, Choice } = await server.ssrLoadModule('/src/kalkulacka/CaseFields.jsx');
  const { default: Results } = await server.ssrLoadModule('/src/kalkulacka/CaseResults.jsx');
  const render=(C, props)=>renderToStaticMarkup(React.createElement(C, props));
  for(const [name,e] of Object.entries(catalogue.entries)) test(`Vykreslení ${name} beze změny textu`,()=>{
    const html=render(Help,{name});
    const expected=renderToStaticMarkup(React.createElement('p',null,e.plain)).slice(3,-4);
    assert(html.includes(expected)); assert(html.includes('Lidsky řečeno:'));
    if(e.legal) assert(html.includes('<summary'));
    assert(!html.includes('<details open'));
  });
  test('Rozbalení odborné vrstvy neleží uvnitř checkbox labelu',()=>{
    const html=render(Choice,{checked:false,onChange:()=>{},helpKey:'alimonyA',children:'Platíte někomu pravidelně výživné?'});
    assert(html.indexOf('</label>')<html.indexOf('data-approved-help'));
    assert(html.includes('aria-describedby=')); assert(!html.includes('checked=""'));
  });
  const fixture=(mode)=>{
    let d={...createDefaultData(),dluhyNezajistene:600000};
    d.prijmy1[0].castka=30000;d.prijmy2[0].castka=25000;
    for(const step of flowFor(d,mode,calculateCase(d,params,mode))) d=confirmSection(d,mode,step,params);
    return d;
  };
  for(const mode of ['jednotlivec','manzele','nezabavitelna']) {
    const data=fixture(mode), results=calculateCase(data,params,mode), status=caseStatus(data,mode,results,params);
    const snapshot=JSON.stringify(data);
    for(const step of status.flow) test(`${mode}/${step}: vysvětlivky nemění vstupní data`,()=>{
      const html=render(Fields,{step,mode,data,results,setData:()=>{},errors:[]});
      assert.equal(JSON.stringify(data),snapshot);
      if(step==='family') {
        assert(html.includes('data-approved-help="'+(mode==='manzele'?'dependentsA':'dependentsSingle')+'"'));
        assert(html.includes('data-approved-help="enforcedAlimonyA"'));
      }
      if(step.startsWith('income')) assert(html.includes('data-approved-help="incomeAmount"'));
      if(step==='debts') assert(html.includes('data-approved-help="unsecuredDebt"'));
    });
    test(`${mode}: výsledek obsahuje původní vysvětlivku odpovídající režimu`,()=>{
      const html=render(Results,{mode,data,results,params});
      assert(html.includes('data-approved-help="'+(mode==='jednotlivec'?'deductionIndividual':mode==='manzele'?'deductionSpouses':'deductionExecution')+'"'));
      assert(status.canExport);assert.equal(JSON.stringify(data),snapshot);
    });
  }
  test('Vypnutí volby stále maže pouze příslušný údaj',()=>{
    const d=fixture('manzele');d.bezneMesicniVyzivne1=2000;d.bezneMesicniVyzivne2=900;
    const changed=toggleOptional(d,'bezneMesicniVyzivne1',false);
    assert.equal(Number(changed.bezneMesicniVyzivne1),0);assert.equal(changed.bezneMesicniVyzivne2,900);
  });
} finally { await server.close(); }
console.log(`Ověření doslovně obnovených vysvětlivek: ${count} kontrol.`);
